# -*- mode: python ; coding: utf-8 -*-
import sys

block_cipher = None


a = Analysis(['_00_CLI.py'],
             pathex=[],
             binaries=[],
             datas=[('icon.ico', '.'),
			  ('version.txt', '.'),
              ('donation.gif', '.'),
              (sys.prefix+r'/tcl/tix8.4.3', 'tcl/tix8.4.3'),
              ('chia_blockchain/chia', 'chia_blockchain/chia'),
              ('gold_blockchain/chia', 'gold_blockchain/chia'),
              ('joker_blockchain/joker', 'joker_blockchain/joker'),
              ('chives_blockchain/chives', 'chives_blockchain/chives'),
              ('skynet_blockchain/skynet', 'skynet_blockchain/skynet'),
              ('staicoin_blockchain/staicoin', 'staicoin_blockchain/staicoin'),
              ('melon_blockchain/melon', 'melon_blockchain/melon'),
			  ('ethgreen_blockchain/ethgreen', 'ethgreen_blockchain/ethgreen'),
              ('silicoin_blockchain/chia', 'silicoin_blockchain/chia'),
              ('clvm_rs_0_1_2', 'clvm_rs_0_1_2'),
              ('clvm_rs_0_1_15', 'clvm_rs_0_1_15')],
             hiddenimports=['tabulate',
							'pyinstaller',
							'PyYAML',
							'aiohttp',
							'aiosqlite',
							'bitstring',
							'blspy',
							'chiabip158',
							'chiapos',
							'chiavdf',
							'skynetpos',
                            'skynetvdf',
							'click',
							'clvm',
							'clvm-tools',
							'colorama',
							'colorlog',
							'concurrent-log-handler',
							'cryptography',
							'dnspython',
							'fasteners',
							'keyrings.cryptfile.cryptfile',
							'watchdog.events',
							'watchdog.observers',
							'websockets',
							'pillow',
							'requests'
			 ],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='_00_CLI',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None,
		  icon='icon.ico' )
