name: build-windows
on: 
    release:
        types: [published]

jobs:
    build:
        runs-on: windows-latest
        
        steps: 
        - uses: actions/checkout@v2
          with:
            submodules: 'recursive'
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with: 
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Build GUI & CLI
          run: |
            python _00_update_version.py "${{ github.event.release.name }}"
            pyinstaller _00_GUI.spec
            pyinstaller _00_CLI.spec
        - name: upload windows artifact GUI
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist/GUI_${{ github.event.release.name }}.exe
            asset_name: GUI_${{ github.event.release.name }}.exe
            asset_content_type: application/zip
        - name: upload windows artifact CLI
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist/CLI_${{ github.event.release.name }}.exe
            asset_name: CLI_${{ github.event.release.name }}.exe
            asset_content_type: application/zip